insert into esegpais(cdpais, nmpais, sgpais) values (4,'Afeganistão','AFG');
insert into esegpais(cdpais, nmpais, sgpais) values (710,'África do Sul','ZAF');
insert into esegpais(cdpais, nmpais, sgpais) values (8,'Albânia','ALB');
insert into esegpais(cdpais, nmpais, sgpais) values (276,'Alemanha','DEU');
insert into esegpais(cdpais, nmpais, sgpais) values (20,'Andorra','AND');
insert into esegpais(cdpais, nmpais, sgpais) values (24,'Angola','AGO');
insert into esegpais(cdpais, nmpais, sgpais) values (660,'Anguilla','AIA');
insert into esegpais(cdpais, nmpais, sgpais) values (28,'Antígua e Barbuda','ATG');
insert into esegpais(cdpais, nmpais, sgpais) values (682,'Arábia Saudita','SAU');
insert into esegpais(cdpais, nmpais, sgpais) values (12,'Argélia','DZA');
insert into esegpais(cdpais, nmpais, sgpais) values (32,'Argentina','ARG');
insert into esegpais(cdpais, nmpais, sgpais) values (51,'Armênia','ARM');
insert into esegpais(cdpais, nmpais, sgpais) values (533,'Aruba','ABW');
insert into esegpais(cdpais, nmpais, sgpais) values (36,'Austrália','AUS');
insert into esegpais(cdpais, nmpais, sgpais) values (40,'Áustria','AUT');
insert into esegpais(cdpais, nmpais, sgpais) values (31,'Azerbaijão','AZE');
insert into esegpais(cdpais, nmpais, sgpais) values (44,'Bahamas','BHS');
insert into esegpais(cdpais, nmpais, sgpais) values (50,'Bangladesh','BGD');
insert into esegpais(cdpais, nmpais, sgpais) values (52,'Barbados','BRB');
insert into esegpais(cdpais, nmpais, sgpais) values (48,'Barein','BHR');
insert into esegpais(cdpais, nmpais, sgpais) values (56,'Bélgica','BEL');
insert into esegpais(cdpais, nmpais, sgpais) values (84,'Belize','BLZ');
insert into esegpais(cdpais, nmpais, sgpais) values (204,'Benin','BEN');
insert into esegpais(cdpais, nmpais, sgpais) values (60,'Bermuda','BMU');
insert into esegpais(cdpais, nmpais, sgpais) values (112,'Bielorússia','BLR');
insert into esegpais(cdpais, nmpais, sgpais) values (68,'Bolívia','BOL');
insert into esegpais(cdpais, nmpais, sgpais) values (535,'Bonaire, Santo Eustáquio e Saba','BES');
insert into esegpais(cdpais, nmpais, sgpais) values (70,'Bósnia-Herzegovina','BIH');
insert into esegpais(cdpais, nmpais, sgpais) values (72,'Botsuana','BWA');
insert into esegpais(cdpais, nmpais, sgpais) values (76,'Brasil','BRA');
insert into esegpais(cdpais, nmpais, sgpais) values (96,'Brunei','BRN');
insert into esegpais(cdpais, nmpais, sgpais) values (100,'Bulgária','BGR');
insert into esegpais(cdpais, nmpais, sgpais) values (854,'Burkina Faso','BFA');
insert into esegpais(cdpais, nmpais, sgpais) values (108,'Burundi','BDI');
insert into esegpais(cdpais, nmpais, sgpais) values (64,'Butão','BTN');
insert into esegpais(cdpais, nmpais, sgpais) values (132,'Cabo Verde','CPV');
insert into esegpais(cdpais, nmpais, sgpais) values (120,'Camarões','CMR');
insert into esegpais(cdpais, nmpais, sgpais) values (116,'Camboja','KHM');
insert into esegpais(cdpais, nmpais, sgpais) values (124,'Canadá','CAN');
insert into esegpais(cdpais, nmpais, sgpais) values (398,'Casaquistão','KAZ');
insert into esegpais(cdpais, nmpais, sgpais) values (634,'Catar','QAT');
insert into esegpais(cdpais, nmpais, sgpais) values (148,'Chade','TCD');
insert into esegpais(cdpais, nmpais, sgpais) values (152,'Chile','CHL');
insert into esegpais(cdpais, nmpais, sgpais) values (156,'China','CHN');
insert into esegpais(cdpais, nmpais, sgpais) values (344,'China, Hong Kong','HKG');
insert into esegpais(cdpais, nmpais, sgpais) values (446,'China, Macao','MAC');
insert into esegpais(cdpais, nmpais, sgpais) values (196,'Chipre','CYP');
insert into esegpais(cdpais, nmpais, sgpais) values (702,'Cingapura','SGP');
insert into esegpais(cdpais, nmpais, sgpais) values (170,'Colômbia','COL');
insert into esegpais(cdpais, nmpais, sgpais) values (174,'Comores','COM');
insert into esegpais(cdpais, nmpais, sgpais) values (178,'Congo','COG');
insert into esegpais(cdpais, nmpais, sgpais) values (408,'Coréia do Norte','PRK');
insert into esegpais(cdpais, nmpais, sgpais) values (410,'Coréia do Sul','KOR');
insert into esegpais(cdpais, nmpais, sgpais) values (384,'Costa do Marfim','CIV');
insert into esegpais(cdpais, nmpais, sgpais) values (188,'Costa Rica','CRI');
insert into esegpais(cdpais, nmpais, sgpais) values (191,'Croácia','HRV');
insert into esegpais(cdpais, nmpais, sgpais) values (192,'Cuba','CUB');
insert into esegpais(cdpais, nmpais, sgpais) values (531,'Curaçao','CUW');
insert into esegpais(cdpais, nmpais, sgpais) values (208,'Dinamarca','DNK');
insert into esegpais(cdpais, nmpais, sgpais) values (262,'Djibouti','DJI');
insert into esegpais(cdpais, nmpais, sgpais) values (212,'Dominica','DMA');
insert into esegpais(cdpais, nmpais, sgpais) values (818,'Egito','EGY');
insert into esegpais(cdpais, nmpais, sgpais) values (222,'El Salvador','SLV');
insert into esegpais(cdpais, nmpais, sgpais) values (784,'Emirados Árabes Unidos','ARE');
insert into esegpais(cdpais, nmpais, sgpais) values (218,'Equador','ECU');
insert into esegpais(cdpais, nmpais, sgpais) values (232,'Eritréia','ERI');
insert into esegpais(cdpais, nmpais, sgpais) values (703,'Eslováquia','SVK');
insert into esegpais(cdpais, nmpais, sgpais) values (705,'Eslovênia','SVN');
insert into esegpais(cdpais, nmpais, sgpais) values (724,'Espanha','ESP');
insert into esegpais(cdpais, nmpais, sgpais) values (840,'Estados Unidos da América','USA');
insert into esegpais(cdpais, nmpais, sgpais) values (233,'Estônia','EST');
insert into esegpais(cdpais, nmpais, sgpais) values (231,'Etiópia','ETH');
insert into esegpais(cdpais, nmpais, sgpais) values (242,'Fiji','FJI');
insert into esegpais(cdpais, nmpais, sgpais) values (608,'Filipinas','PHL');
insert into esegpais(cdpais, nmpais, sgpais) values (246,'Finlândia','FIN');
insert into esegpais(cdpais, nmpais, sgpais) values (250,'França','FRA');
insert into esegpais(cdpais, nmpais, sgpais) values (266,'Gabão','GAB');
insert into esegpais(cdpais, nmpais, sgpais) values (270,'Gâmbia','GMB');
insert into esegpais(cdpais, nmpais, sgpais) values (288,'Gana','GHA');
insert into esegpais(cdpais, nmpais, sgpais) values (268,'Geórgia','GEO');
insert into esegpais(cdpais, nmpais, sgpais) values (292,'Gibraltar','GIB');
insert into esegpais(cdpais, nmpais, sgpais) values (308,'Granada','GRD');
insert into esegpais(cdpais, nmpais, sgpais) values (300,'Grécia','GRC');
insert into esegpais(cdpais, nmpais, sgpais) values (304,'Groenlândia','GRL');
insert into esegpais(cdpais, nmpais, sgpais) values (316,'Guam','GUM');
insert into esegpais(cdpais, nmpais, sgpais) values (320,'Guatemala','GTM');
insert into esegpais(cdpais, nmpais, sgpais) values (831,'Guernsey','GGY');
insert into esegpais(cdpais, nmpais, sgpais) values (328,'Guiana','GUY');
insert into esegpais(cdpais, nmpais, sgpais) values (254,'Guiana Francesa','GUF');
insert into esegpais(cdpais, nmpais, sgpais) values (324,'Guiné','GIN');
insert into esegpais(cdpais, nmpais, sgpais) values (226,'Guiné Equatorial','GNQ');
insert into esegpais(cdpais, nmpais, sgpais) values (624,'Guiné-Bissau','GNB');
insert into esegpais(cdpais, nmpais, sgpais) values (332,'Haiti','HTI');
insert into esegpais(cdpais, nmpais, sgpais) values (528,'Holanda','NLD');
insert into esegpais(cdpais, nmpais, sgpais) values (340,'Honduras','HND');
insert into esegpais(cdpais, nmpais, sgpais) values (348,'Hungria','HUN');
insert into esegpais(cdpais, nmpais, sgpais) values (887,'Iêmen','YEM');
insert into esegpais(cdpais, nmpais, sgpais) values (833,'Ilha de Man','IMN');
insert into esegpais(cdpais, nmpais, sgpais) values (312,'Ilha Guadalupe','GLP');
insert into esegpais(cdpais, nmpais, sgpais) values (574,'Ilha Norfolk','NFK');
insert into esegpais(cdpais, nmpais, sgpais) values (638,'Ilha Reunião','REU');
insert into esegpais(cdpais, nmpais, sgpais) values (248,'Ilhas Alanda','ALA');
insert into esegpais(cdpais, nmpais, sgpais) values (136,'Ilhas Cayman','CYM');
insert into esegpais(cdpais, nmpais, sgpais) values (184,'Ilhas Cook','COK');
insert into esegpais(cdpais, nmpais, sgpais) values (830,'Ilhas do Canal','');
insert into esegpais(cdpais, nmpais, sgpais) values (234,'Ilhas Faeroe','FRO');
insert into esegpais(cdpais, nmpais, sgpais) values (238,'Ilhas Falkland','FLK');
insert into esegpais(cdpais, nmpais, sgpais) values (580,'Ilhas Marianas','MNP');
insert into esegpais(cdpais, nmpais, sgpais) values (584,'Ilhas Marshall','MHL');
insert into esegpais(cdpais, nmpais, sgpais) values (90,'Ilhas Salomão','SLB');
insert into esegpais(cdpais, nmpais, sgpais) values (796,'Ilhas Turks e Caicos','TCA');
insert into esegpais(cdpais, nmpais, sgpais) values (850,'Ilhas Virgens','VIR');
insert into esegpais(cdpais, nmpais, sgpais) values (92,'Ilhas Virgens Britânicas','VGB');
insert into esegpais(cdpais, nmpais, sgpais) values (876,'Ilhas Wallis e Futuna','WLF');
insert into esegpais(cdpais, nmpais, sgpais) values (356,'Índia','IND');
insert into esegpais(cdpais, nmpais, sgpais) values (360,'Indonésia','IDN');
insert into esegpais(cdpais, nmpais, sgpais) values (364,'Irã','IRN');
insert into esegpais(cdpais, nmpais, sgpais) values (368,'Iraque','IRQ');
insert into esegpais(cdpais, nmpais, sgpais) values (372,'Irlanda','IRL');
insert into esegpais(cdpais, nmpais, sgpais) values (352,'Islândia','ISL');
insert into esegpais(cdpais, nmpais, sgpais) values (376,'Israel','ISR');
insert into esegpais(cdpais, nmpais, sgpais) values (380,'Itália','ITA');
insert into esegpais(cdpais, nmpais, sgpais) values (388,'Jamaica','JAM');
insert into esegpais(cdpais, nmpais, sgpais) values (392,'Japão','JPN');
insert into esegpais(cdpais, nmpais, sgpais) values (832,'Jersey','JEY');
insert into esegpais(cdpais, nmpais, sgpais) values (400,'Jordânia','JOR');
insert into esegpais(cdpais, nmpais, sgpais) values (296,'Kiribati','KIR');
insert into esegpais(cdpais, nmpais, sgpais) values (414,'Kuwait','KWT');
insert into esegpais(cdpais, nmpais, sgpais) values (418,'Laos','LAO');
insert into esegpais(cdpais, nmpais, sgpais) values (426,'Lesoto','LSO');
insert into esegpais(cdpais, nmpais, sgpais) values (428,'Letônia','LVA');
insert into esegpais(cdpais, nmpais, sgpais) values (422,'Líbano','LBN');
insert into esegpais(cdpais, nmpais, sgpais) values (430,'Libéria','LBR');
insert into esegpais(cdpais, nmpais, sgpais) values (434,'Líbia','LBY');
insert into esegpais(cdpais, nmpais, sgpais) values (438,'Liechtenstein','LIE');
insert into esegpais(cdpais, nmpais, sgpais) values (440,'Lituânia','LTU');
insert into esegpais(cdpais, nmpais, sgpais) values (442,'Luxemburgo','LUX');
insert into esegpais(cdpais, nmpais, sgpais) values (807,'Macedônia','MKD');
insert into esegpais(cdpais, nmpais, sgpais) values (450,'Madagáscar','MDG');
insert into esegpais(cdpais, nmpais, sgpais) values (458,'Malásia','MYS');
insert into esegpais(cdpais, nmpais, sgpais) values (454,'Malauí','MWI');
insert into esegpais(cdpais, nmpais, sgpais) values (462,'Maldivas','MDV');
insert into esegpais(cdpais, nmpais, sgpais) values (466,'Mali','MLI');
insert into esegpais(cdpais, nmpais, sgpais) values (470,'Malta','MLT');
insert into esegpais(cdpais, nmpais, sgpais) values (504,'Marrocos','MAR');
insert into esegpais(cdpais, nmpais, sgpais) values (474,'Martinica','MTQ');
insert into esegpais(cdpais, nmpais, sgpais) values (480,'Maurício','MUS');
insert into esegpais(cdpais, nmpais, sgpais) values (478,'Mauritânia','MRT');
insert into esegpais(cdpais, nmpais, sgpais) values (175,'Mayotte','MYT');
insert into esegpais(cdpais, nmpais, sgpais) values (484,'México','MEX');
insert into esegpais(cdpais, nmpais, sgpais) values (104,'Mianma','MMR');
insert into esegpais(cdpais, nmpais, sgpais) values (583,'Micronésia','FSM');
insert into esegpais(cdpais, nmpais, sgpais) values (508,'Moçambique','MOZ');
insert into esegpais(cdpais, nmpais, sgpais) values (498,'Moldávia','MDA');
insert into esegpais(cdpais, nmpais, sgpais) values (492,'Mônaco','MCO');
insert into esegpais(cdpais, nmpais, sgpais) values (496,'Mongólia','MNG');
insert into esegpais(cdpais, nmpais, sgpais) values (499,'Montenegro','MNE');
insert into esegpais(cdpais, nmpais, sgpais) values (500,'Montserrat','MSR');
insert into esegpais(cdpais, nmpais, sgpais) values (516,'Namíbia','NAM');
insert into esegpais(cdpais, nmpais, sgpais) values (520,'Nauru','NRU');
insert into esegpais(cdpais, nmpais, sgpais) values (524,'Nepal','NPL');
insert into esegpais(cdpais, nmpais, sgpais) values (558,'Nicarágua','NIC');
insert into esegpais(cdpais, nmpais, sgpais) values (562,'Níger','NER');
insert into esegpais(cdpais, nmpais, sgpais) values (566,'Nigéria','NGA');
insert into esegpais(cdpais, nmpais, sgpais) values (570,'Niue','NIU');
insert into esegpais(cdpais, nmpais, sgpais) values (578,'Noruega','NOR');
insert into esegpais(cdpais, nmpais, sgpais) values (540,'Nova Caledônia','NCL');
insert into esegpais(cdpais, nmpais, sgpais) values (554,'Nova Zelândia','NZL');
insert into esegpais(cdpais, nmpais, sgpais) values (512,'Omã','OMN');
insert into esegpais(cdpais, nmpais, sgpais) values (585,'Palau','PLW');
insert into esegpais(cdpais, nmpais, sgpais) values (275,'Palestina','PSE');
insert into esegpais(cdpais, nmpais, sgpais) values (591,'Panamá','PAN');
insert into esegpais(cdpais, nmpais, sgpais) values (598,'Papua Nova Guiné','PNG');
insert into esegpais(cdpais, nmpais, sgpais) values (586,'Paquistão','PAK');
insert into esegpais(cdpais, nmpais, sgpais) values (600,'Paraguai','PRY');
insert into esegpais(cdpais, nmpais, sgpais) values (604,'Peru','PER');
insert into esegpais(cdpais, nmpais, sgpais) values (612,'Pitcairn','PCN');
insert into esegpais(cdpais, nmpais, sgpais) values (258,'Polinésia Francesa','PYF');
insert into esegpais(cdpais, nmpais, sgpais) values (616,'Polônia','POL');
insert into esegpais(cdpais, nmpais, sgpais) values (630,'Porto Rico','PRI');
insert into esegpais(cdpais, nmpais, sgpais) values (620,'Portugal','PRT');
insert into esegpais(cdpais, nmpais, sgpais) values (404,'Quênia','KEN');
insert into esegpais(cdpais, nmpais, sgpais) values (417,'Quirguistão','KGZ');
insert into esegpais(cdpais, nmpais, sgpais) values (826,'Reino Unido','GBR');
insert into esegpais(cdpais, nmpais, sgpais) values (140,'República Centro Africana','CAF');
insert into esegpais(cdpais, nmpais, sgpais) values (180,'República Democrática do Congo','COD');
insert into esegpais(cdpais, nmpais, sgpais) values (214,'República Dominicana','DOM');
insert into esegpais(cdpais, nmpais, sgpais) values (203,'República Tcheca','CZE');
insert into esegpais(cdpais, nmpais, sgpais) values (642,'Romênia','ROU');
insert into esegpais(cdpais, nmpais, sgpais) values (646,'Ruanda','RWA');
insert into esegpais(cdpais, nmpais, sgpais) values (643,'Rússia (Federação Russa)','RUS');
insert into esegpais(cdpais, nmpais, sgpais) values (732,'Saara Ocidental','ESH');
insert into esegpais(cdpais, nmpais, sgpais) values (663,'Saint Martin (parte francesa)','MAF');
insert into esegpais(cdpais, nmpais, sgpais) values (534,'Saint Martin (parte holandesa)','SXM');
insert into esegpais(cdpais, nmpais, sgpais) values (666,'Saint Pierre e Miquelon','SPM');
insert into esegpais(cdpais, nmpais, sgpais) values (882,'Samoa','WSM');
insert into esegpais(cdpais, nmpais, sgpais) values (16,'Samoa Americana','ASM');
insert into esegpais(cdpais, nmpais, sgpais) values (674,'San Marino','SMR');
insert into esegpais(cdpais, nmpais, sgpais) values (654,'Santa Helena','SHN');
insert into esegpais(cdpais, nmpais, sgpais) values (662,'Santa Lúcia','LCA');
insert into esegpais(cdpais, nmpais, sgpais) values (652,'São Bartolomeu','BLM');
insert into esegpais(cdpais, nmpais, sgpais) values (659,'São Cristóvão e Nevis','KNA');
insert into esegpais(cdpais, nmpais, sgpais) values (678,'São Tome e Príncipe','STP');
insert into esegpais(cdpais, nmpais, sgpais) values (670,'São Vicente e Granadinas','VCT');
insert into esegpais(cdpais, nmpais, sgpais) values (680,'Sark',' ');
insert into esegpais(cdpais, nmpais, sgpais) values (690,'Seichelles','SYC');
insert into esegpais(cdpais, nmpais, sgpais) values (686,'Senegal','SEN');
insert into esegpais(cdpais, nmpais, sgpais) values (694,'Serra Leoa','SLE');
insert into esegpais(cdpais, nmpais, sgpais) values (688,'Sérvia','SRB');
insert into esegpais(cdpais, nmpais, sgpais) values (760,'Síria','SYR');
insert into esegpais(cdpais, nmpais, sgpais) values (706,'Somália','SOM');
insert into esegpais(cdpais, nmpais, sgpais) values (144,'Sri Lanka','LKA');
insert into esegpais(cdpais, nmpais, sgpais) values (748,'Suazilândia','SWZ');
insert into esegpais(cdpais, nmpais, sgpais) values (728,'Sudão do Sul','SSD');
insert into esegpais(cdpais, nmpais, sgpais) values (729,'Sudão','SDN');
insert into esegpais(cdpais, nmpais, sgpais) values (752,'Suécia','SWE');
insert into esegpais(cdpais, nmpais, sgpais) values (756,'Suíça','CHE');
insert into esegpais(cdpais, nmpais, sgpais) values (740,'Suriname','SUR');
insert into esegpais(cdpais, nmpais, sgpais) values (744,'Svalbard e Jan Mayen Islands','SJM');
insert into esegpais(cdpais, nmpais, sgpais) values (762,'Tadjiquistão','TJK');
insert into esegpais(cdpais, nmpais, sgpais) values (764,'Tailândia','THA');
insert into esegpais(cdpais, nmpais, sgpais) values (834,'Tanzânia','TZA');
insert into esegpais(cdpais, nmpais, sgpais) values (626,'Timor Leste','TLS');
insert into esegpais(cdpais, nmpais, sgpais) values (768,'Togo','TGO');
insert into esegpais(cdpais, nmpais, sgpais) values (772,'Tokelau','TKL');
insert into esegpais(cdpais, nmpais, sgpais) values (776,'Tonga','TON');
insert into esegpais(cdpais, nmpais, sgpais) values (780,'Trinidad e Tobago','TTO');
insert into esegpais(cdpais, nmpais, sgpais) values (788,'Tunísia','TUN');
insert into esegpais(cdpais, nmpais, sgpais) values (795,'Turcomenistão','TKM');
insert into esegpais(cdpais, nmpais, sgpais) values (792,'Turquia','TUR');
insert into esegpais(cdpais, nmpais, sgpais) values (798,'Tuvalu','TUV');
insert into esegpais(cdpais, nmpais, sgpais) values (804,'Ucrânia','UKR');
insert into esegpais(cdpais, nmpais, sgpais) values (800,'Uganda','UGA');
insert into esegpais(cdpais, nmpais, sgpais) values (858,'Uruguai','URY');
insert into esegpais(cdpais, nmpais, sgpais) values (860,'Uzbequistão','UZB');
insert into esegpais(cdpais, nmpais, sgpais) values (548,'Vanuatu','VUT');
insert into esegpais(cdpais, nmpais, sgpais) values (336,'Vaticano','VAT');
insert into esegpais(cdpais, nmpais, sgpais) values (862,'Venezuela','VEN');
insert into esegpais(cdpais, nmpais, sgpais) values (704,'Vietnã','VNM');
insert into esegpais(cdpais, nmpais, sgpais) values (894,'Zâmbia','ZMB');
insert into esegpais(cdpais, nmpais, sgpais) values (716,'Zimbábue','ZWE');
